name: CrysTool
channels:
  - conda-forge
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - anyio=4.9.0=pyh29332c3_0
  - appnope=0.1.4=pyhd8ed1ab_1
  - argon2-cffi=23.1.0=pyhd8ed1ab_1
  - argon2-cffi-bindings=21.2.0=py310h493c2e1_5
  - arrow=1.3.0=pyhd8ed1ab_1
  - asttokens=3.0.0=pyhd8ed1ab_1
  - async-lru=2.0.5=pyh29332c3_0
  - attrs=25.3.0=pyh71513ae_0
  - babel=2.17.0=pyhd8ed1ab_0
  - beautifulsoup4=4.13.3=pyha770c72_0
  - bleach=6.2.0=pyh29332c3_4
  - bleach-with-css=6.2.0=h82add2a_4
  - brotli=1.1.0=hd74edd7_2
  - brotli-bin=1.1.0=hd74edd7_2
  - brotli-python=1.1.0=py310hb4ad77e_2
  - bzip2=1.0.8=h99b78c6_7
  - ca-certificates=2025.1.31=hf0a4a13_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - certifi=2025.1.31=pyhd8ed1ab_0
  - cffi=1.17.1=py310h497396d_0
  - charset-normalizer=3.4.1=pyhd8ed1ab_0
  - colorama=0.4.6=pyhd8ed1ab_1
  - comm=0.2.2=pyhd8ed1ab_1
  - contourpy=1.3.1=py310h7f4e7e6_0
  - cpython=3.10.16=py310hd8ed1ab_1
  - cycler=0.12.1=pyhd8ed1ab_1
  - debugpy=1.8.13=py310h853098b_0
  - decorator=5.2.1=pyhd8ed1ab_0
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - exceptiongroup=1.2.2=pyhd8ed1ab_1
  - fonttools=4.56.0=py310hc74094e_0
  - fqdn=1.5.1=pyhd8ed1ab_1
  - freetype=2.13.3=h1d14073_0
  - future=1.0.0=pyhd8ed1ab_2
  - gmp=6.3.0=h7bae524_2
  - gmpy2=2.1.5=py310h805dbd7_3
  - h11=0.14.0=pyhd8ed1ab_1
  - h2=4.2.0=pyhd8ed1ab_0
  - hpack=4.1.0=pyhd8ed1ab_0
  - httpcore=1.0.7=pyh29332c3_1
  - httpx=0.28.1=pyhd8ed1ab_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - idna=3.10=pyhd8ed1ab_1
  - importlib-metadata=8.6.1=pyha770c72_0
  - importlib-resources=6.5.2=pyhd8ed1ab_0
  - importlib_resources=6.5.2=pyhd8ed1ab_0
  - ipykernel=6.29.5=pyh57ce528_0
  - ipython=8.34.0=pyh907856f_0
  - ipywidgets=8.1.5=pyhd8ed1ab_1
  - isoduration=20.11.0=pyhd8ed1ab_1
  - jedi=0.19.2=pyhd8ed1ab_1
  - jinja2=3.1.6=pyhd8ed1ab_0
  - joblib=1.4.2=pyhd8ed1ab_1
  - json5=0.10.0=pyhd8ed1ab_1
  - jsonpointer=3.0.0=py310hbe9552e_1
  - jsonschema=4.23.0=pyhd8ed1ab_1
  - jsonschema-specifications=2024.10.1=pyhd8ed1ab_1
  - jsonschema-with-format-nongpl=4.23.0=hd8ed1ab_1
  - jupyter=1.1.1=pyhd8ed1ab_1
  - jupyter-lsp=2.2.5=pyhd8ed1ab_1
  - jupyter_client=8.6.3=pyhd8ed1ab_1
  - jupyter_console=6.6.3=pyhd8ed1ab_1
  - jupyter_core=5.7.2=pyh31011fe_1
  - jupyter_events=0.12.0=pyh29332c3_0
  - jupyter_server=2.15.0=pyhd8ed1ab_0
  - jupyter_server_terminals=0.5.3=pyhd8ed1ab_1
  - jupyterlab_pygments=0.3.0=pyhd8ed1ab_2
  - jupyterlab_server=2.27.3=pyhd8ed1ab_1
  - jupyterlab_widgets=3.0.13=pyhd8ed1ab_1
  - kiwisolver=1.4.7=py310h7306fd8_0
  - krb5=1.21.3=h237132a_0
  - latexcodec=2.0.1=pyh9f0ad1d_0
  - lcms2=2.17=h7eeda09_0
  - lerc=4.0.0=h9a09cb3_0
  - libblas=3.9.0=31_h10e41b3_openblas
  - libbrotlicommon=1.1.0=hd74edd7_2
  - libbrotlidec=1.1.0=hd74edd7_2
  - libbrotlienc=1.1.0=hd74edd7_2
  - libcblas=3.9.0=31_hb3479ef_openblas
  - libcxx=20.1.1=ha82da77_0
  - libdeflate=1.23=hec38601_0
  - libedit=3.1.20250104=pl5321hafb1f1b_0
  - libffi=3.4.2=h3422bc3_5
  - libgfortran=5.0.0=14_2_0_h6c33f7e_1
  - libgfortran5=14.2.0=h6c33f7e_1
  - libjpeg-turbo=3.0.0=hb547adb_1
  - liblapack=3.9.0=31_hc9a63f6_openblas
  - liblzma=5.6.4=h39f12f2_0
  - libopenblas=0.3.29=openmp_hf332438_0
  - libpng=1.6.47=h3783ad8_0
  - libsodium=1.0.20=h99b78c6_0
  - libsqlite=3.49.1=h3f77e49_2
  - libtiff=4.7.0=h551f018_3
  - libwebp-base=1.5.0=h2471fea_0
  - libxcb=1.17.0=hdb1d25a_0
  - libzlib=1.3.1=h8359307_2
  - llvm-openmp=20.1.1=hdb05f8b_1
  - markupsafe=3.0.2=py310hc74094e_1
  - matplotlib=3.10.1=py310hb6292c7_0
  - matplotlib-base=3.10.1=py310hadbac3a_0
  - matplotlib-inline=0.1.7=pyhd8ed1ab_1
  - mistune=3.1.3=pyh29332c3_0
  - monty=2025.3.3=pyhd8ed1ab_0
  - mpc=1.3.1=h8f1351a_1
  - mpfr=4.2.1=hb693164_3
  - mpmath=1.3.0=pyhd8ed1ab_1
  - munkres=1.1.4=pyh9f0ad1d_0
  - narwhals=1.32.0=pyhd8ed1ab_0
  - nbclient=0.10.2=pyhd8ed1ab_0
  - nbconvert-core=7.16.6=pyh29332c3_0
  - nbformat=5.10.4=pyhd8ed1ab_1
  - ncurses=6.5=h5e97a16_3
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - networkx=3.4.2=pyh267e887_2
  - notebook-shim=0.2.4=pyhd8ed1ab_1
  - numpy=2.2.4=py310h4d83441_0
  - openjpeg=2.5.3=h8a3d83b_0
  - openssl=3.4.1=h81ee809_0
  - overrides=7.7.0=pyhd8ed1ab_1
  - packaging=24.2=pyhd8ed1ab_2
  - palettable=3.3.3=pyhd8ed1ab_1
  - pandas=2.2.3=py310hfd37619_1
  - parso=0.8.4=pyhd8ed1ab_1
  - pexpect=4.9.0=pyhd8ed1ab_1
  - pickleshare=0.7.5=pyhd8ed1ab_1004
  - pillow=11.1.0=py310h61efb56_0
  - pip=25.0.1=pyh8b19718_0
  - pkgutil-resolve-name=1.3.10=pyhd8ed1ab_2
  - platformdirs=4.3.7=pyh29332c3_0
  - plotly=6.0.1=pyhd8ed1ab_0
  - prometheus_client=0.21.1=pyhd8ed1ab_0
  - prompt-toolkit=3.0.50=pyha770c72_0
  - prompt_toolkit=3.0.50=hd8ed1ab_0
  - psutil=7.0.0=py310h078409c_0
  - pthread-stubs=0.4=hd74edd7_1002
  - ptyprocess=0.7.0=pyhd8ed1ab_1
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - pybtex=0.24.0=pyhd8ed1ab_3
  - pycparser=2.22=pyh29332c3_1
  - pygments=2.19.1=pyhd8ed1ab_0
  - pyobjc-core=11.0=py310h4e4eb3c_0
  - pyobjc-framework-cocoa=11.0=py310h4e4eb3c_0
  - pyparsing=3.2.3=pyhd8ed1ab_1
  - pysocks=1.7.1=pyha55dd90_7
  - python=3.10.16=h870587a_1_cpython
  - python-dateutil=2.9.0.post0=pyhff2d567_1
  - python-fastjsonschema=2.21.1=pyhd8ed1ab_0
  - python-tzdata=2025.2=pyhd8ed1ab_0
  - python_abi=3.10=5_cp310
  - pytz=2024.1=pyhd8ed1ab_0
  - pyyaml=6.0.2=py310hc74094e_2
  - pyzmq=26.3.0=py310h6d25ecc_0
  - qhull=2020.2=h420ef59_5
  - readline=8.2=h1d1bf99_2
  - referencing=0.36.2=pyh29332c3_0
  - requests=2.32.3=pyhd8ed1ab_1
  - rfc3339-validator=0.1.4=pyhd8ed1ab_1
  - rfc3986-validator=0.1.1=pyh9f0ad1d_0
  - rpds-py=0.24.0=py310h31b3829_0
  - ruamel.yaml=0.18.10=py310h078409c_0
  - ruamel.yaml.clib=0.2.8=py310hf9df320_1
  - scipy=1.15.2=py310h32ab4ed_0
  - send2trash=1.8.3=pyh31c8845_1
  - setuptools=75.8.2=pyhff2d567_0
  - six=1.17.0=pyhd8ed1ab_0
  - sniffio=1.3.1=pyhd8ed1ab_1
  - spglib=2.6.0=py310h80559d0_0
  - stack_data=0.6.3=pyhd8ed1ab_1
  - sympy=1.13.3=pyh2585a3b_105
  - tabulate=0.9.0=pyhd8ed1ab_2
  - terminado=0.18.1=pyh31c8845_0
  - tinycss2=1.4.0=pyhd8ed1ab_0
  - tk=8.6.13=h5083fa2_1
  - tomli=2.2.1=pyhd8ed1ab_1
  - tornado=6.4.2=py310h078409c_0
  - tqdm=4.67.1=pyhd8ed1ab_1
  - traitlets=5.14.3=pyhd8ed1ab_1
  - types-python-dateutil=2.9.0.20241206=pyhd8ed1ab_0
  - typing-extensions=4.13.0=h9fa5a19_1
  - typing_extensions=4.13.0=pyh29332c3_1
  - typing_utils=0.1.0=pyhd8ed1ab_1
  - tzdata=2025b=h78e105d_0
  - uncertainties=3.2.2=pyhd8ed1ab_2
  - unicodedata2=16.0.0=py310h078409c_0
  - uri-template=1.3.0=pyhd8ed1ab_1
  - urllib3=2.3.0=pyhd8ed1ab_0
  - wcwidth=0.2.13=pyhd8ed1ab_1
  - webcolors=24.11.1=pyhd8ed1ab_0
  - webencodings=0.5.1=pyhd8ed1ab_3
  - websocket-client=1.8.0=pyhd8ed1ab_1
  - wheel=0.45.1=pyhd8ed1ab_1
  - widgetsnbextension=4.0.13=pyhd8ed1ab_1
  - xorg-libxau=1.0.12=h5505292_0
  - xorg-libxdmcp=1.1.5=hd74edd7_0
  - yaml=0.2.5=h3422bc3_2
  - zeromq=4.3.5=hc1bb282_7
  - zipp=3.21.0=pyhd8ed1ab_1
  - zstandard=0.23.0=py310h078409c_1
  - zstd=1.5.7=h6491c7d_2
  - pip:
      - aiofiles==22.1.0
      - aioitertools==0.12.0
      - aiosqlite==0.21.0
      - annotated-types==0.7.0
      - bcrypt==4.3.0
      - blinker==1.9.0
      - boto3==1.37.23
      - botocore==1.37.23
      - cachelib==0.13.0
      - click==8.1.8
      - cryptography==44.0.2
      - crystal-toolkit==2024.10.22
      - crystaltoolkit-extension==0.6.0
      - dash==3.0.1
      - dash-mp-components==0.4.47
      - dnspython==2.7.0
      - emmet-core==0.84.6rc6
      - entrypoints==0.4
      - executing==2.2.0
      - flask==3.0.3
      - flask-caching==2.3.1
      - frozendict==2.4.6
      - imageio==2.37.0
      - ipython-genutils==0.2.0
      - itsdangerous==2.2.0
      - jmespath==1.0.1
      - jsonlines==4.0.0
      - jupyter-client==7.4.9
      - jupyter-server-fileid==0.9.3
      - jupyter-server-ydoc==0.8.0
      - jupyter-ydoc==0.2.5
      - jupyterlab==3.6.8
      - lazy-loader==0.4
      - maggma==0.71.5
      - mongomock==4.3.0
      - mp-api==0.45.3
      - msgpack==1.1.0
      - nbclassic==1.2.0
      - notebook==6.5.7
      - orjson==3.10.16
      - pandocfilters==1.5.1
      - paramiko==3.5.1
      - pydantic==2.11.1
      - pydantic-core==2.33.0
      - pydantic-settings==2.8.1
      - pydash==8.0.5
      - pymatgen==2024.10.22
      - pymongo==4.10.1
      - pynacl==1.5.0
      - python-dotenv==1.1.0
      - python-json-logger==3.3.0
      - retrying==1.3.4
      - s3transfer==0.11.4
      - scikit-image==0.25.2
      - scikit-learn==1.6.1
      - sentinels==1.0.0
      - shapely==2.0.7
      - smart-open==7.1.0
      - soupsieve==2.6
      - sshtunnel==0.4.0
      - threadpoolctl==3.6.0
      - tifffile==2025.3.13
      - typing-inspection==0.4.0
      - werkzeug==3.0.6
      - wrapt==1.17.2
      - y-py==0.6.2
      - ypy-websocket==0.8.4
prefix: /opt/miniconda3/envs/CrysTool
